### ISSUE TITLE
local folder not handled correctly when there is depth

### ISSUE THREAD

**Issue by gregoryheeren** [horochx/deploy-via-scp#3]
I'm using the following action

    - uses: horochx/deploy-via-scp@master
      with:
        local: src/www/
        remote: /var/www/somefolder
        host: myhost.com
        port: 22
        user: deployuser
        key: ${{ secrets.DEPLOY_KEY }}

Observed behavior: On the remote server, a folder /var/www/somefolder/www is created which contains all files from the local src/www folder

Expected behavior: On the remote server, the files from the local src/www should be directly in /var/www/somefolder/ (without creating a subfolder "www")

**Comment by horochx** [comment]
Use `src/www/*` instead of `src/www/`, this will solve the problem~

**Comment by horochx** [comment]
Based on your feedback, I have updated the README, thank you~
